version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    depends_on:
      - mysql
    networks:
      - laravel
    ports:
    - "8080:8000"
    expose:
      - "9000"

  # nginx:
  #   image: nginx:latest
  #   container_name: laravel-nginx
  #   ports:
  #     - "8000:80"
  #   volumes:
  #     - .:/var/www
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - app
  #   networks:
  #     - laravel

  mysql:
    image: mysql:latest
    container_name: laravel-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
    - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
